creation_rules:
  - path_regex: '\.env$'
    age: >-
      age1zptpgxhs9chnkudu69qut2hn706pmyngasvaz4ppf452un2x7p2ss6j96f,
      age1xrl5h3076kq470ce68s2h5cevqx2zf2j38acjmrmkq2c23ycduksu7qym4,
      age1xwekswqnd6thy2rygk5k7d3c6e85z4vl4l79j7am5mv7nldn7cls2ejraa,
      age1v5f3def5nelp38m2jmk2uu349acswdpnm4qzfc6kf5te8fvh4q0qwsy2fg,
      age1yr95gsufrrfz2ckyws5xx36kyu5h0wcaast5jg7zp2js3wv59pusq3jvlu,
      age1psmayn76drks67a493l46gnuruaj7yw6u5qa043pqwg59596qq9sfh6etd

# 1. Ayushman
# 2. Sandipan
# 3. Krishnendu
# 4. Bhumika
# 5. Divyanshu
# 6. Karan
