/// <reference types="@cloudflare/workers-types" />

/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: de0c734494ccfa2caff52a58a47a2c05)
interface __BaseEnv_CloudflareEnv {
  CACHE: KVNamespace;
  RATE_LIMITS: KVNamespace;
  DB: D1Database;
  ASSETS: Fetcher;
  EMAIL_OUTBOUND_QUEUE: Queue;
  NEXT_PUBLIC_APP_URL: 'https://opensource.elixpo.com';
  NEXT_PUBLIC_ACCOUNTS_URL: 'https://accounts.elixpo.com';
  NEXT_PUBLIC_GITHUB_REPOSITORY: 'https://github.com/elixpo/opensource';
  NEXT_PUBLIC_ELIXPO_CLIENT_ID: string;
  ELIXPO_CLIENT_SECRET: string;
  GITHUB_APP_ID: string;
  GITHUB_APP_PRIVATE_KEY: string;
  GITHUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'NEXT_PUBLIC_APP_URL'
        | 'NEXT_PUBLIC_ACCOUNTS_URL'
        | 'NEXT_PUBLIC_GITHUB_REPOSITORY'
        | 'NEXT_PUBLIC_ELIXPO_CLIENT_ID'
        | 'ELIXPO_CLIENT_SECRET'
        | 'GITHUB_APP_ID'
        | 'GITHUB_APP_PRIVATE_KEY'
        | 'GITHUB_WEBHOOK_SECRET'
      >
    > {}
}
